# Generated by Django 4.1.2 on 2022-11-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_homework_task_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
