# Generated by Django 4.1.2 on 2022-11-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainer_owner'),
        ('course', '0003_task_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='course_id',
            new_name='associated_course',
        ),
        migrations.AddField(
            model_name='course',
            name='associated_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
    ]
